"""AI Governance demo runner.

Generates a deterministic AI plugin, validates it against policy rules,
registers the plugin function with the core registry, runs a build that
uses the plugin-provided scalar, computes a deterministic build hash,
and writes a compliance report.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path
from typing import Any

import yaml

from demos.ai_governance_demo.plugin_validator import validate_plugin_or_raise

_DEMO_DIR = Path(__file__).parent

_PLUGIN_SOURCE = '''\
"""AI-generated plugin example -- deterministic revenue scaler.

This plugin was generated by an AI system and conforms to the
fin123 plugin governance policy.
"""

from fin123.functions.registry import register_scalar

PLUGIN_META = {
    "version": 1,
    "author": "ai-system",
    "generated_by": "ai",
    "model": "demo-llm",
    "timestamp": "2025-01-01T00:00:00Z",
    "prompt_hash": "demo_prompt_hash_v1",
    "deterministic": True,
}


def scale_revenue(base: float, factor: float) -> float:
    """Deterministic revenue scaling transform."""
    return base * factor


def register() -> dict:
    """Register this plugin with the fin123 engine."""
    register_scalar("ai_scale_revenue")(scale_revenue)
    return {"name": "ai_revenue_scaler", "version": PLUGIN_META["version"]}
'''

# Workbook spec that uses the ai_scale_revenue function
_WORKBOOK_SPEC: dict[str, Any] = {
    "version": 1,
    "params": {
        "ticker": "DEMO",
        "base_revenue": 100000.0,
        "growth_factor": 1.08,
    },
    "tables": {
        "assumptions": {
            "source": "inputs/assumptions.csv",
            "format": "csv",
        },
    },
    "outputs": [
        {
            "name": "scaled_revenue",
            "type": "scalar",
            "func": "ai_scale_revenue",
            "args": {
                "base": 100000.0,
                "factor": 1.08,
            },
        },
        {
            "name": "projected_value",
            "type": "scalar",
            "formula": "=scaled_revenue * 10",
        },
    ],
    "assertions": [
        {
            "name": "revenue_positive",
            "expr": "$scaled_revenue > 0",
            "severity": "error",
        },
    ],
}


def compute_deterministic_hash(input_dict: dict[str, Any]) -> str:
    """Compute SHA-256 hash from deterministic JSON serialization."""
    canonical = json.dumps(input_dict, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _register_plugin_in_process() -> None:
    """Execute the plugin's register() function in the current process.

    This registers ai_scale_revenue with the core scalar function registry
    so that Workbook.run() can resolve it during evaluation.
    """
    from fin123.functions.registry import register_scalar

    def scale_revenue(base: float, factor: float) -> float:
        """Deterministic revenue scaling transform."""
        return base * factor

    register_scalar("ai_scale_revenue")(scale_revenue)


def run_demo(output_dir: Path | None = None) -> dict[str, Any]:
    """Execute the AI governance demo end-to-end.

    Args:
        output_dir: Directory to write output files. Defaults to the demo directory.

    Returns:
        Compliance report dict.
    """
    from fin123.workbook import Workbook

    out = output_dir or _DEMO_DIR

    # 1. Generate deterministic plugin code
    plugin_path = out / "ai_generated_plugin_example.py"
    plugin_path.write_text(_PLUGIN_SOURCE)

    # 2. Validate plugin against policy
    validate_plugin_or_raise(_PLUGIN_SOURCE)
    validation_status = "PASS"

    # 3. Register the plugin function with the core registry
    _register_plugin_in_process()

    # 4. Load demo model config
    config_path = _DEMO_DIR / "demo_config.yaml"
    config = yaml.safe_load(config_path.read_text())
    schema_version = config["schema_version"]

    # 5. Set up a temporary project and run a build using the plugin
    project_dir = out / "_demo_project"
    if project_dir.exists():
        shutil.rmtree(project_dir)
    project_dir.mkdir(parents=True)

    # Write workbook spec
    wb_path = project_dir / "workbook.yaml"
    wb_path.write_text(yaml.dump(_WORKBOOK_SPEC, default_flow_style=False, sort_keys=False))
    (project_dir / "fin123.yaml").write_text("max_runs: 50\nmode: dev\n")

    # Create input data
    inputs_dir = project_dir / "inputs"
    inputs_dir.mkdir()
    (inputs_dir / "assumptions.csv").write_text(
        "category,item,amount\nrevenue,base,100000.0\n"
    )

    # Create required directories
    for subdir in ("runs", "artifacts", "snapshots", "sync_runs", "cache"):
        (project_dir / subdir).mkdir(exist_ok=True)

    # Create initial snapshot
    from fin123.versioning import SnapshotStore

    store = SnapshotStore(project_dir)
    store.save_snapshot(wb_path.read_text())

    # Run build
    wb = Workbook(project_dir)
    result = wb.run()
    meta = json.loads((result.run_dir / "run_meta.json").read_text())

    # Extract the plugin-computed output value
    plugin_output_value = result.scalars.get("scaled_revenue")

    # 6. Compute deterministic build hash
    build_hash = compute_deterministic_hash({
        "plugin_code": _PLUGIN_SOURCE,
        "model_config": _WORKBOOK_SPEC,
        "schema_version": schema_version,
    })

    # 7. Write artifact manifest (demo-local registration)
    artifact_manifest = {
        "artifact_name": "ai_governance_demo",
        "artifact_version": "v1",
        "build_hash": build_hash,
        "export_hash": meta.get("export_hash", ""),
        "plugin_output_value": plugin_output_value,
        "plugin_version": 1,
        "schema_version": schema_version,
    }
    manifest_path = out / "artifact_manifest.json"
    manifest_path.write_text(
        json.dumps(artifact_manifest, indent=2, sort_keys=True) + "\n"
    )

    # 8. Write compliance report
    compliance_report = {
        "ai_generated": True,
        "artifact_version": "v1",
        "compliance_status": "APPROVED",
        "deterministic_build_hash": build_hash,
        "export_hash": meta.get("export_hash", ""),
        "generated_by": "ai",
        "model": "demo-llm",
        "plugin_output_value": plugin_output_value,
        "plugin_version": 1,
        "policy_checks": [
            {"check": "plugin_meta_fields", "status": "PASS"},
            {"check": "forbidden_imports", "status": "PASS"},
            {"check": "network_patterns", "status": "PASS"},
            {"check": "register_entrypoint", "status": "PASS"},
            {"check": "deterministic_transform", "status": "PASS"},
            {"check": "engine_build_executed", "status": "PASS"},
        ],
        "prompt_hash": "demo_prompt_hash_v1",
        "validation_status": validation_status,
    }
    report_path = out / "compliance_report_output.json"
    report_path.write_text(
        json.dumps(compliance_report, indent=2, sort_keys=True) + "\n"
    )

    # 9. Print deterministic output
    print(f"Validation: {validation_status}")
    print(f"Plugin Output (scaled_revenue): {plugin_output_value}")
    print(f"Deterministic Build Hash: {build_hash}")
    print(f"Export Hash: {meta.get('export_hash', '')}")
    print("Artifact Version: v1")
    print("AI Generated: true")
    print("Compliance Status: APPROVED")

    # Cleanup
    shutil.rmtree(project_dir)

    return compliance_report
